name = "TeukEvolution"
uuid = "db7c6640-4064-41ef-bd4d-b1d7936fee3a"
authors = ["Justin L. Ripley"]
version = "0.1.0"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Jacobi = "83f21c0b-4282-5fbc-9e3f-f6da3d2e584c"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
FastGaussQuadrature = "0.4"
Jacobi = "0.5"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
