outdir = "med"

nx = 128 
ny = 24
nt = 20000
ts = 400  # save every ts time steps

psi_spin    = -2 # spin-weight of linear evolution scalar
psi_falloff = -1 # falloff (in r) of linear evolution scalar

m_vals = [-2,2]

id_kind = "gaussian"

runtype = "reconstruction"

id_l_ang = [2,2]
id_ru = [3.0,  3.0]
id_rl = [-3.0,-3.0] 
id_width = [6.0,6.0]
id_amp = [
	[0.0,0.0],
	[0.4,0.0]
]  
# format: [real part, imaginary part]

cl  = 1.0 # compactification scale
cfl = 0.5 # CFL number
bhs = 0.0 # black hole spin 
bhm = 1.0 # black hole mass
